basePath: /api/1.0.0
consumes: [application/json]
host: localhost:8080
info: {title: RAS API Gateway, version: 1.0.0}
paths:
  /info:
    get:
      description: Basic service health check
      operationId: info
      responses:
        200: {description: documented info structure}
        500: {description: server error}
      x-swagger-router-controller: ras_api_gateway.proxy_controller
  /surveys/todo/{id}:
    get:
      description: Aggregated call based on a party identifier
      operationId: survey_todo
      parameters:
      - {description: The party id, in: path, name: id, required: true, type: string}
      - {description: The list of statuses we're interested in, in: query, name: status_filter,
        required: true, type: string}
      responses:
        200: {description: status supplied}
        500: {description: server error}
      x-swagger-router-controller: ras_api_gateway.proxy_controller
produces: [application/json]
schemes: [http, https]
swagger: '2.0'
