swagger: "2.0"
host: "localhost:8080"

info:
  title: OAuth Example
  version: "1.0"

paths:
  /secret:
    get:
      summary: Return secret string
      operationId: app.get_secret
      responses:
        200:
          description: secret response
          schema:
            type: string
      security:
        # enable authentication and require the "uid" scope for this endpoint
        - oauth2: ['uid']

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    x-tokenInfoUrl: http://localhost:5000/oauth/token
    tokenUrl: http://localhost:5000/oauth/token
    scopes:
      uid: Unique identifier of the user accessing the service.
